version : "3.3"

services :
  pol-redis :
    image :   redis
    ports :
      - 6379:6379
    restart : always
    networks :
      - polinsight_network

  pol-mariadb :
    image :   mariadb
    ports :
      - 3306:3306
    environment :
      - MYSQL_USER=polinsight
      - MYSQL_PASSWORD=polinsight
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polinsight
    restart : always
    networks :
      - polinsight_network

  pol-mongodb :
    image :   mongo
    ports :
      - 27017:27017
    restart : always
    networks :
      - my_net
  pol-app :
    image : polinsight/app
    ports :
      - 8080:8080
    networks :
      - polinsight_network
    environment :
      - maria_host="pol-mariadb"
      - mongo_host="pol-mongodb"
      - redis_host="pol-redis"
      - profile=prod
    depends_on :
      - pol-redis
      - pol-mariadb
      - pol-mongodb

networks :
  polinsight_network :