version: "3.7"

services:
  ####### common #######
  redis:
    # container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - first_network
      - second_network

  ####### boundary #######
  maria_first:
    image: mariadb
    # container_name: maria_first
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polinsight
    ports:
      - "1306:3306"
    networks:
      - first_network

  mongodb_first:
    image: mongo
    # container_name: mongodb_first
    ports:
      - "12017:27017"
    networks:
      - first_network

  first_app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - first_network
    ports:
      - 81:8080
    environment:
      profile: ff
      SPRING_DATASOURCE_URL: jdbc:mysql://maria_first:3306/polinsight?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always
    depends_on:
      - maria_first
      - mongodb_first
      - redis

  ####### boundary #######
  # maria_second:
  #   image: maria
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=polinsight
  #   ports:
  #     - "2306:3306"
  #   networks:
  #     - second_network
  # mongodb_second:
  #   image: mongo
  #   ports:
  #     - "22017:27017"
  #   networks:
  #     - second_network
  # second_app:
  #   build:
  #     context: .
  #   ports:
  #     - 82:8080
  #   environment:
  #     - profile=dev
  #   depends_on:
  #     - maria_second
  #     - mongodb_second
  #     - redis

####### boundary #######

networks:
  first_network:
  second_network:
