spring :
  profiles :
    group :
      dev :  common, devdb, dev
      prod : common, proddb, prod
---
server :
  port : 8080
  servlet :
    context-path :             /
    encoding :
      charset : UTF-8
    application-display-name : dnslab_polinsight
    session :
      cookie :
        http-only : true
  error :
    path : /templates/error

spring :
  servlet :
    multipart :
      max-file-size :    102400KB
      max-request-size : 102400KB

  security :
    oauth2 :
      client :
        provider :
          #          google :
          naver :
            authorization-uri :   https://nid.naver.com/oauth2.0/authorize
            token_uri :           https://nid.naver.com/oauth2.0/token
            user-info-uri :       https://openapi.naver.com/v1/nid/me
            user-name-attribute : response # 네이버에서 반환하는 데이터 구조를 보면 알 수 있음
          kakao :
            authorization-uri :   https://kauth.kakao.com/oauth/authorize
            token-uri :           https://kauth.kakao.com/oauth/token
            user-info-uri :       https://kapi.kakao.com/v2/user/me
            user-name-attribute : id
        registration :
          google :
            clientId :            dda
            clientSecret :        dd
            redirectUriTemplate : "{baseUrl}/oauth2/callback/{registrationId}"
            scope :
              - email
              - profile
          naver :
            client-name :              Naver
            client-id :                dd
            client-secret :            dd
            authorization-grant-type : authorization_code
            redirect-uri :             "{baseUrl}/login/oauth2/code/{registrationId}"
            scope :
              - name
              - email
              - profile_image
          kakao :
            client-name :                  Kakao
            client-id :                    dd
            client-secret :                dd
            authorization-grant-type :     authorization_code
            redirect-uri :                 "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method : POST
            scope :
              - profile
              - account_email

  mvc :
    static-path-pattern : /static/**
  web :
    resources :
      static-locations : classpath:/static
      add-mappings :     true

  cache :
    type : redis

  mail :
    host :  # smtp address
    port :  # smtp port
    username :  # smtp 등록 계정
    password :  # smtp 등록 계정의 패스워드
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true
  config :
    activate :
      on-profile : common

  output :
    ansi :
      enabled : always

logging :
  file :
    name : ./polinsight_logs.log


file :
  upload :
    baseLocation : "./upload_dir/"

custom :
  permission :
    resources :
      - /css/**
      - /js/**
      - /img/**
      - favicon.ico

    admin :
      - /admin/**

    template :
      - /
      - /signup
      - /join
      - /index
      - /error/**
      - /loginSuccess
      - /login
      - /user/**
      - /findpwd
      - /terms
      - /wholesign
      - /boards**
      - /panel
      - /point**
      - /denied
      - /moreinfo
      - /dologin
      - /actuator**
      - /h2**
      - /boards/**
      - /board**
      - /api/**
      - /actuator/**
      - /panelagreement
      - /surveys/**
  api :
    url :         "https://api.surveymonkey.net/v3/" # 서베이 몽키 API 주소
    accessToken : "uX2r-rEuS8sFuxabPuSDfDkD2KWu459vOQg588cu6qatlX1QS5uURCVTvip1rKzk7ApktG.RWz.vRu69oVmx9WNd.hq0RZ2knTfXf-Fopw7K8f.-EGOgAD-IOXOnFQwH"


management :
  endpoints :
    enabled-by-default : true

    web :
      exposure :
        include : "*"
    jmx :
      exposure :
        include : health, info
  endpoint :
    info :
      enabled : true
    health :
      show-components : always
      show-details :    always

---
spring :
  datasource :
    username :          root
    password :          root
    url :               jdbc:mariadb://localhost:3306/polinsight_db
    driver-class-name : org.mariadb.jdbc.Driver


  data :
    mongodb :
      uri : mongodb://localhost:27017/polinsight

  redis :
    host : localhost
    port : 6379

  config :
    activate :
      on-profile : devdb
---
spring :
  datasource :
    username :          polinsight
    password :          polinsight
    url :               jdbc:mariadb://pol-mariadb:3306/polinsight?useSSL=false
    driver-class-name : org.mariadb.jdbc.Driver

  data :
    mongodb :
      uri : mongodb://pol-mongodb:27017/polinsight

  redis :
    host : pol-redis
    port : 6379

  config :
    activate :
      on-profile : proddb
---
spring :
  config :
    activate :
      on-profile : dev
  jpa :
    hibernate :
      ddl-auto : create-drop
    properties :
      format_sql : true
    show-sql :     true
    generate-ddl : true

  banner :
    location : banner-dev.txt

  session :
    store-type : none

  devtools :
    restart :
      poll-interval : 1s

server :
  port : 8080
  servlet :
    session :
      timeout : 5m
---
spring :
  config :
    activate :
      on-profile : prod
  jpa :
    hibernate :
      ddl-auto : update
    generate-ddl : false


  banner :
    location : banner-prod.txt
  session :
    store-type : redis
server :
  port : 8080
  servlet :
    session :
      timeout : 15m
