server :
  port : 8080
  servlet :
    context-path :             /
    encoding :
      charset : UTF-8
    application-display-name : PolInsight
    session :
      cookie :
        http-only : true
  error :
    path : /templates/error


spring :
  datasource :
    username :          root
    password :          root
    url :               jdbc:mariadb://localhost:3308/polinsight
    driver-class-name : org.mariadb.jdbc.Driver

  jpa :
    show-sql : true
    hibernate :
      ddl-auto : update

    data :
      mongodb :
        host :     localhost
        password : 27017
        database : polinsight

  security :
    oauth2 :
      registration :
        google :
          clientId :
          clientSecret :
          redirectUriTemplate : "{baseUrl}/oauth2/callback/{registrationId}"
          scope :
            - email
            - profile
        naver :
          clientName :               naver
          clientId :
          clientSecret :
          authorization-grant-type : authorization_code
          redirectUriTemplate :      "{baseUrl}/oauth2/callback/{registrationId}"
          scope :
            - email
            - profile_image
        kakao :
          clientName :                   kakao
          clientId :
          authorization-grant-type :     authorization_code
          redirectUriTemplate :          "{baseUrl}/oauth2/callback/{registrationId}"
          client-authentication-method : POST
          scope :
            - account_email
            - profile
      provider :
        google :
        naver :
          authorizationUri :
          tokenUri :
          userInfoUri :
          user-name-attribute :
        kakao :
          authorizationUri :
          tokenUri :
          userInfoUri :
          user-name-attribute :
  mvc :
    static-path-pattern : /static/**
  web :
    resources :
      static-locations : classpath:/static/
      add-mappings :     true