server :
  port : 8080
  servlet :
    context-path :             /
    encoding :
      charset : UTF-8
    application-display-name : PolInsight
    session :
      cookie :
        http-only : true
  error :
    path : /templates/error

spring :

  redis:
    host: localhost
    port: 6379

  datasource:
    username: pol
    password: 1234
    url: jdbc:mariadb://localhost:3306/polinsight
    driver-class-name: org.mariadb.jdbc.Driver


  jpa :
    show-sql : true
    hibernate :
      ddl-auto : update

    data :
      mongodb :
        host :     localhost
        password : 27017
        database : polinsight
    properties:
      hibernate:
        format_sql: true

  security :
    oauth2 :
      client :
        provider :
          #          google :
          naver :
            authorization-uri :   https://nid.naver.com/oauth2.0/authorize
            token_uri :           https://nid.naver.com/oauth2.0/token
            user-info-uri :       https://openapi.naver.com/v1/nid/me
            user-name-attribute : response # 네이버에서 반환하는 데이터 구조를 보면 알 수 있음
          kakao :
            authorization-uri :   https://kauth.kakao.com/oauth/authorize
            token-uri :           https://kauth.kakao.com/oauth/token
            user-info-uri :       https://kapi.kakao.com/v2/user/me
            user-name-attribute : id
        registration :
          google :
            clientId :            61528740066-719taq23e9rhlg15k3srr5sd2nm20kgq.apps.googleusercontent.com
            clientSecret :        0c0jJjvKxeACkG9ZWM3GWTQu
            redirectUriTemplate : "{baseUrl}/oauth2/callback/{registrationId}"
            scope :
              - email
              - profile
          naver :
            client-name :              Naver
            client-id :                j0J7LuyWcfHKCF_IQLdn
            client-secret :            _UEdUG089J
            authorization-grant-type : authorization_code
            redirect-uri :             "{baseUrl}/login/oauth2/code/{registrationId}"
            scope :
              - name
              - email
              - profile_image
          kakao :
            client-name :                  Kakao
            client-id :                    3f9fc6c7c1b07e9181061f800d659bdf
            client-secret :                7FDxfbG3gBUMwoAGRT29usEyUEI0Fq6n
            authorization-grant-type :     authorization_code
            redirect-uri :                 "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method : POST
            scope :
              - profile
              - account_email
  mvc :
    static-path-pattern : /static/**
  web :
    resources :
      static-locations : classpath:/static/
      add-mappings :     true
  banner :
    location : classpath:banner-dev.txt
custom :
  permission :
    resources : /css/**, /js/**, /img/**
    admin :     /swagger-ui/**
    template :  /signup, /index, /, /404, loginSuccess, /loginpage, /user/**, /findpassword