spring :
  profiles :
    group :
      dev :  common, devdb, dev
      prod : common, proddb, prod
---
server :
  port : 8080
  servlet :
    context-path :             /
    encoding :
      charset : UTF-8
    application-display-name : dnslab_polinsight
    session :
      cookie :
        http-only : true
  error :
    path : /templates/error

spring :
  servlet :
    multipart :
      max-file-size :    100MB
      max-request-size : 100MB
  mvc :
    static-path-pattern : /static/**
    hiddenmethod :
      filter :
        enabled : true
  web :
    resources :
      static-locations : classpath:/static
      add-mappings :     true


  cache :
    type : redis

  mail :
    host :     smtp.gmail.com # smtp address
    port :     587 # smtp port
    username : jnudnslab@gmail.com # smtp 등록 계정
    password : dnslab@3438 # smtp 등록 계정의 패스워드
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true
  config :
    activate :
      on-profile : common

  output :
    ansi :
      enabled : always
  thymeleaf :
    servlet :
      content-type : "*/*"

custom :
  permission :
    resources :
      - /css/**
      - /js/**
      - /img/**
      - /favicon.ico

  api :
    url :         "https://api.surveymonkey.net/v3/" # 서베이 몽키 API 주소
    accessToken : "Yfs4qichR8C.2TU62kmrA7HDksZf2437YUcjFCwWbCg-u5LVmHDzbEM5Obl4JJJQF8.AhqCoOVyz13J5QRv2Ry8sA6NlPhX8T8Nif8cbP59YhRPA2sYchaSMroAvfiQD"
  callback :
    base : "http://localhost:8080"
  hash :
    passwordsalt : ${random.value}
    pointsalt :    ${random.value}


management :
  endpoints :
    enabled-by-default : true

    web :
      exposure :
        include : "*"
    jmx :
      exposure :
        include : health, info
  endpoint :
    info :
      enabled : true
    health :
      show-components : always
      show-details :    always

---
spring :
  datasource :
    username :          root
    password :          root
    url :               jdbc:mariadb://localhost:3306/polinsight
    driver-class-name : org.mariadb.jdbc.Driver
    hikari :
      pool-name :         Test DBCP Pool
      maximum-pool-size : 10

  redis :
    host : localhost
    port : 6379

  config :
    activate :
      on-profile : devdb
---
spring :
  config :
    activate :
      on-profile : dev


  jpa :
    properties :
      hibernate :
        ddl-auto :   validate
        format_sql : true
    generate-ddl : true
    show-sql :     true


  banner :
    location : banner-dev.txt

  session :
    store-type : none

  devtools :
    restart :
      poll-interval : 1s

  thymeleaf :
    cache : false

server :
  port : 8080
  servlet :
    session :
      timeout : 5m

custom :
  callback :
    base : "http://localhost:8080"
file :
  upload :
    #    baseLocation: "/Users/yunjun/IntelliJProjects/polinsight/upload-dir/"
    #    image: "/Users/yunjun/IntelliJProjects/polinsight/upload-dir/images/"
    #    thumbnail: "/Users/yunjun/IntelliJProjects/polinsight/upload-dir/thumbnails/"
    #    file: "/Users/yunjun/IntelliJProjects/polinsight/upload-dir/files/"
    baseLocation : "C:\\upload_test\\"
    image :        "C:\\upload_test\\images\\"
    thumbnail :    "C:\\upload_test\\thumbnails\\"
    file :         "C:\\upload_test\\files\\"
    address :      "http://localhost:8080/uploads/"
---
spring :
  datasource :
    username :          polinsight
    password :          polinsight
    url :               jdbc:mariadb://pol-mariadb:3306/polinsight?useSSL=false
    driver-class-name : org.mariadb.jdbc.Driver
    hikari :
      maximum-pool-size : 200
      pool-name :         Polinsight DBCP Pool

  redis :
    host : pol-redis
    port : 6379

  config :
    activate :
      on-profile : proddb

---
spring :
  config :
    activate :
      on-profile : prod
  jpa :
    hibernate :
      ddl-auto : validate
    generate-ddl : false

  banner :
    location : banner-prod.txt
  session :
    store-type : redis
server :
  port : 8080
  servlet :
    session :
      timeout : 15m

#logging :
#  file :
#    name : /app/logs/polinsight_logs.log
#  level :
#    root : info
#    com :
#      dns :
#        polinsight :
#          service : info


custom :
  callback :
    base : "http://dnslab.iptime.org"

file :
  upload :
    baseLocation : "/app/data/"
    image :        "/app/data/images/"
    thumbnail :    "/app/data/thumbnails/"
    file :         "/app/data/files/"
    address :      "http://dnslab.iptime.org/uploads/"